server {
    listen 80;
    server_name api.justinkozlowski.me;

    location / {
        # Update rate limiting to match the new rate of 15 requests per minute
        limit_req zone=gemini_limit burst=5 nodelay;

        proxy_pass https://gemini.google.com;
        proxy_set_header Host gemini.google.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Developer-Key $GOOGLE_GEMINI_API_KEY;
    }
}