env GOOGLE_GEMINI_API_KEY;

worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    # Update the shared memory zone for rate limiting to 15 requests per minute
    limit_req_zone $binary_remote_addr zone=gemini_limit:10m rate=15r/m;

    include /etc/nginx/conf.d/*.conf;
}